"""Write the legacy-Keras checkpoint fixture of ``tests/test_tensorpot.py``.

Run it on a tree that still uses legacy Keras 2 (``tf_keras``; the tree before DEPS3), from the repository
root of that tree, with ``tf_keras`` installed::

    PYTHONPATH=<untouched tree> python <this tree>/tests/legacy_keras_checkpoint/make_fixture.py <this tree>/tests/legacy_keras_checkpoint

It builds a very small GRACE model (4,810 parameters) with seeded weights, takes three Adam steps (amsgrad,
weight decay, EMA) with seeded gradients, and saves a checkpoint flagged as a mid-epoch save, with step 3 and
epoch 1. ``weights.npz`` holds the model weights that the checkpoint stores, in ``variables_to_train`` order,
so that a test can compare a restore without reading the checkpoint by any other means. The fixture is not
regenerated by the tests; a new Keras line does not change what a legacy writer produced.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

import tensorpotential  # noqa: F401, I001  (before TensorFlow)
import tensorflow as tf

from tensorpotential.potentials import get_preset
from tensorpotential.tensorpot import TensorPotential
from tests.seeded_weights import seed_trainable_variables

OPTIONS = {
    "learning_rate": 0.5,
    "amsgrad": True,
    "weight_decay": 0.1,
    "use_ema": True,
    "ema_momentum": 0.9,
}
MODEL = {
    "lmax": 0,
    "embedding_size": 4,
    "n_rad_max": 3,
    "n_rad_base": 4,
    "n_mlp_dens": 2,
    "max_order": 2,
}
ELEMENTS = {"Be": 0, "Li": 1}
STEPS, EPOCH = 3, 1


def main(out_dir: Path) -> None:
    """Write ``checkpoint.*``, ``weights.npz`` and ``manifest.json`` into ``out_dir``."""
    uses_legacy_keras = tf.keras.optimizers.Adam.__module__.startswith("tf_keras")
    if not uses_legacy_keras:
        raise SystemExit(
            "this tree does not use legacy Keras: run it on the tree before DEPS3"
        )
    instructions = get_preset("GRACE_1LAYER_v1_24")(
        element_map=ELEMENTS, **MODEL
    ).get_instructions()
    tp = TensorPotential(
        instructions,
        param_dtype=tf.float32,
        fit_config={"optimizer": "Adam", "opt_params": OPTIONS},
    )
    variables = tp.model.variables_to_train
    seed_trainable_variables(tp.model)
    for step in range(STEPS):
        grads = [
            tf.constant(
                np.random.default_rng([5, step, i]).standard_normal(v.shape),
                dtype=v.dtype,
            )
            for i, v in enumerate(variables)
        ]
        tp.optimizer.apply_gradients(zip(grads, variables))
    tp.step, tp.epoch = STEPS, EPOCH
    tp.save_checkpoint(checkpoint_name=str(out_dir / "checkpoint"), is_mid_epoch=True)
    np.savez(out_dir / "weights.npz", *[v.numpy() for v in variables])
    manifest = {
        "writer": f"tf_keras {__import__('importlib.metadata').metadata.version('tf_keras')}",
        "tensorflow": tf.__version__,
        "model": {"preset": "GRACE_1LAYER_v1_24", "elements": ELEMENTS, **MODEL},
        "param_dtype": "float32",
        "optimizer": OPTIONS,
        "steps": STEPS,
        "epoch": EPOCH,
        "mid_epoch_save": True,
        "variables": [[v.name, list(v.shape)] for v in variables],
    }
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=1) + "\n")


if __name__ == "__main__":
    main(Path(sys.argv[1]))
