"""Option matrix of the instruction classes seen in a set of ``model.yaml`` files (yaml only, no TensorFlow).

A row is one (class, option, kind of value). The kind keeps the type the yaml holds: ``ls_max`` is an
``int`` in one file and a ``list[int]`` in another, and the two need different handling in a twin.
Categorical kinds (``null``, ``bool``, ``str``) list every value seen, ``list[str]`` the strings in the lists,
numeric kinds the range; other collections give only the kind. The ``metadata`` block of the wrapped yaml
format is scanned as the class ``<metadata>``.

``classify`` gives each row its status against the decisions in
``tensorpotential/torch_backend/spec/options.py`` (loaded by path, so that TensorFlow is not imported):
``supported``, ``ignored`` (a key the TF constructor swallows), ``rejected`` with the reason, or ``unclassified``,
which means the matrix is incomplete. The exit status is 1 when a row is unclassified.

Usage::

    python tools/scan_options.py FILE_OR_DIR... [--json out.json] [--markdown out.md]

Without an output option the matrix is printed as Markdown.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Any

import yaml

METADATA_CLASS = "<metadata>"
SKIPPED_KEYS = frozenset({"name", "__metadata__", "saved_at"})
CATEGORICAL_KINDS = frozenset({"null", "bool", "str", "list[str]"})
NUMERIC_KINDS = frozenset({"int", "float"})
OPTIONS_MODULE = (
    Path(__file__).resolve().parents[1]
    / "tensorpotential/torch_backend/spec/options.py"
)
PATH_PREFIX = "tensorpotential.instructions."
HEADER = """# Option matrix of the model.yaml files

Generated by `tools/scan_options.py` (yaml only, no TensorFlow) from `tests/data/model_yamls/*.yaml`,
`tests/model_grace.yaml`, `tests/model_grace_2L_omat.yaml` and `tests/model_grace_2L_omat_large_base.yaml`;
regenerate with

    python tools/scan_options.py tests/data/model_yamls tests/model_grace*.yaml \\
        --markdown docs/torch_backend/spec/option_matrix.md

The statuses are the decisions of `tensorpotential/torch_backend/spec/options.py`: `supported` (a twin
implements it), `ignored` (a key the TF constructor accepts and never reads), `rejected` (with the reason). A
value that no scanned in-scope model uses is rejected by default (closed-world policy, rule R3). `unclassified`
must not occur: `tests/test_options.py` fails on it, and on a stale copy of this file.
"""


@dataclass(frozen=True)
class Row:
    """One (class, option, kind) cell of the matrix."""

    cls: str
    option: str
    kind: str
    values: tuple[Any, ...]
    low: float | None
    high: float | None
    files: tuple[str, ...]
    count: int

    def as_dict(self) -> dict[str, Any]:
        """JSON-ready form of the row."""
        return {
            "class": self.cls,
            "option": self.option,
            "kind": self.kind,
            "values": list(self.values),
            "low": self.low,
            "high": self.high,
            "files": list(self.files),
            "count": self.count,
        }


def value_kind(value: Any) -> str:
    """Type name of a yaml value, with the element type of lists and dicts (``list[int]``, ``dict[str,int]``)."""
    if value is None:
        return "null"
    if isinstance(value, dict):
        if "_instruction_" in value:
            return "ref"
        return f"dict[{_joined(value.keys())},{_joined(value.values())}]"
    if isinstance(value, list):
        return f"list[{_joined(value)}]"
    return type(value).__name__


def _joined(items: Any) -> str:
    kinds = sorted({value_kind(item) for item in items})
    return "|".join(kinds) if kinds else "empty"


def instruction_dicts(data: Any) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    """Split loaded yaml into its ``metadata`` block and the list of instruction dicts.

    Mirrors ``instructions.base._extract_instructions_data`` for the three formats: wrapped
    (``metadata`` + ``instructions``), flat dict (possibly with an ``__metadata__`` key) and the very old list.
    """
    if isinstance(data, list):
        return {}, list(data)
    if "instructions" in data:
        return dict(data.get("metadata") or {}), list(data["instructions"].values())
    flat = {k: v for k, v in data.items() if k != "__metadata__"}
    return dict(data.get("__metadata__") or {}), list(flat.values())


def _observations(path: Path) -> list[tuple[str, str, Any]]:
    """(class, option, value) triples of one yaml file; the class is the full ``__cls__`` path."""
    with path.open() as handle:
        metadata, instructions = instruction_dicts(yaml.safe_load(handle))
    found = [
        (METADATA_CLASS, key, value)
        for key, value in metadata.items()
        if key not in SKIPPED_KEYS
    ]
    for ins in instructions:
        cls = ins["__cls__"]
        found.append((cls, "__cls__", cls))
        found.extend(
            (cls, key, value)
            for key, value in ins.items()
            if key not in SKIPPED_KEYS | {"__cls__"}
        )
    return found


def _row(key: tuple[str, str, str], seen: list[tuple[str, Any]]) -> Row:
    cls, option, kind = key
    values: set[Any] = set()
    if kind == "list[str]":
        values = {item for _, v in seen for item in v}
    elif kind in CATEGORICAL_KINDS:
        values = {v for _, v in seen}
    numbers = [v for _, v in seen] if kind in NUMERIC_KINDS else []
    return Row(
        cls=cls,
        option=option,
        kind=kind,
        values=tuple(sorted(values, key=repr)),
        low=min(numbers) if numbers else None,
        high=max(numbers) if numbers else None,
        files=tuple(sorted({name for name, _ in seen})),
        count=len(seen),
    )


def scan(paths: list[Path]) -> list[Row]:
    """The option matrix of the given yaml files, sorted by class, option and kind."""
    grouped: dict[tuple[str, str, str], list[tuple[str, Any]]] = defaultdict(list)
    for path in paths:
        for cls, option, value in _observations(path):
            grouped[cls, option, value_kind(value)].append((path.name, value))
    return [_row(key, grouped[key]) for key in sorted(grouped)]


def expand(targets: list[Path]) -> list[Path]:
    """Yaml files named by ``targets``, sorted by name and without repeats; a directory contributes its ``*.yaml`` files."""
    files: set[Path] = set()
    for target in targets:
        files.update(target.glob("*.yaml") if target.is_dir() else [target])
    return sorted(files, key=lambda path: (path.name, str(path)))


def load_options(path: Path = OPTIONS_MODULE) -> ModuleType:
    """The options module loaded by file path, which does not import ``tensorpotential`` (and so TensorFlow)."""
    spec = importlib.util.spec_from_file_location("scan_options_spec", path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module  # dataclasses look the module up by name
    spec.loader.exec_module(module)
    return module


def _accepts(rule: Any, row: Row) -> bool:
    """Whether ``rule`` (an ``OptionRule``) allows every value of the row."""
    if row.kind not in rule.kinds:
        return False
    if rule.values is None:
        return True
    if row.values:
        return all(v in rule.values for v in row.values)
    if row.low is not None:
        return all(v in rule.values for v in (row.low, row.high))
    return True


def _rejection(options: ModuleType, row: Row) -> str | None:
    for rejection in options.REJECTED_OPTIONS.get(row.cls, {}).get(row.option, ()):
        if rejection.kind == row.kind:
            return rejection.reason
    return None


def classify(row: Row, options: ModuleType) -> tuple[str, str]:
    """Status of a row (``supported``, ``ignored``, ``rejected`` or ``unclassified``) and the reason, if any."""
    if row.cls in options.REJECTED_CLASSES:
        return "rejected", options.REJECTED_CLASSES[row.cls]
    rules = (
        options.MODEL_OPTIONS
        if row.cls == METADATA_CLASS
        else options.SUPPORTED_OPTIONS.get(row.cls)
    )
    if rules is None:
        return "unclassified", "class not in SUPPORTED_OPTIONS or REJECTED_CLASSES"
    if row.option == "__cls__":
        return "supported", ""
    rule = rules.get(row.option)
    if rule is not None and _accepts(rule, row):
        return (
            ("ignored", "accepted, not read by the constructor")
            if rule.ignored
            else ("supported", "")
        )
    reason = _rejection(options, row)
    if reason is not None:
        return "rejected", reason
    return (
        "unclassified",
        "value not accepted by the rule and not rejected with a reason",
    )


def _cell(row: Row) -> str:
    if row.values:
        return ", ".join(f"`{json.dumps(v)}`" for v in row.values)
    if row.low is not None:
        return f"{row.low:g}" if row.low == row.high else f"{row.low:g} to {row.high:g}"
    return ""


def blockers(path: Path, options: ModuleType) -> list[str]:
    """What keeps a yaml out of the first twin set: its rejected classes and rejected option values."""
    found: set[str] = set()
    for row in scan([path]):
        short = row.cls.removeprefix(PATH_PREFIX)
        if row.cls in options.REJECTED_CLASSES:
            if row.option == "__cls__":
                found.add(short)
        elif classify(row, options)[0] == "rejected":
            found.add(f"{short}.{row.option}")
    return sorted(found)


def to_markdown(files: list[Path], options: ModuleType) -> str:
    """The matrix as Markdown: a summary of each yaml, then one row per (class, option, kind).

    ``files`` and ``instructions`` count the yaml files and the instructions holding the cell.
    """
    lines = [
        HEADER,
        "## Files",
        "",
        "| file | blockers (rejected classes and values) |",
        "|---|---|",
    ]
    lines.extend(
        f"| {path.name} | {', '.join(blockers(path, options)) or 'none'} |"
        for path in files
    )
    lines.extend([
        "",
        "## Matrix",
        "",
        "| class | option | kind | values or range | files | instructions | status |",
    ])
    lines.append("|---|---|---|---|---|---|---|")
    for r in scan(files):
        status, reason = classify(r, options)
        if r.cls in options.REJECTED_CLASSES and r.option != "__cls__":
            continue  # the rejection of the class covers its options
        option, kind, cell = (
            ("all options", "", "")
            if r.option == "__cls__" and status == "rejected"
            else (r.option, r.kind, _cell(r))
        )
        text = f"{status}: {reason}" if reason else status
        lines.append(
            f"| {r.cls.removeprefix(PATH_PREFIX)} | {option} | {kind} | {cell} | {len(r.files)} | {r.count} | {text} |"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    """Command line entry point; the status is 1 when a row is unclassified."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("targets", nargs="+", type=Path)
    parser.add_argument("--json", type=Path, help="write the rows as JSON")
    parser.add_argument("--markdown", type=Path, help="write the Markdown table")
    args = parser.parse_args(argv)
    files = expand(args.targets)
    rows = scan(files)
    options = load_options()
    if args.json:
        args.json.write_text(json.dumps([r.as_dict() for r in rows], indent=1) + "\n")
    table = to_markdown(files, options)
    if args.markdown:
        args.markdown.write_text(table)
    if not (args.json or args.markdown):
        sys.stdout.write(table)
    unclassified = [r for r in rows if classify(r, options)[0] == "unclassified"]
    for r in unclassified:
        sys.stderr.write(f"unclassified: {r.cls} {r.option} {r.kind} {r.values}\n")
    return 1 if unclassified else 0


if __name__ == "__main__":
    sys.exit(main())
